# Generated by Django 2.2.3 on 2019-08-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='items_json',
        ),
        migrations.AddField(
            model_name='orders',
            name='address1',
            field=models.CharField(default=7, max_length=1000),
            preserve_default=False,
        ),
    ]
